name: CI/CD - FastAPI Serverless API

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build, Push Docker, and Deploy with Terraform
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: quantum-api
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Gerar versão da imagem
        id: version
        run: |
          DATE=$(date +%Y%m%d)
          SHORT_SHA=${GITHUB_SHA::7}
          IMAGE_TAG="v${DATE}-${SHORT_SHA}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_URI=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build e tag da imagem Docker
        run: |
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY:latest $IMAGE_URI

      - name: Push imagem para o ECR
        run: |
          docker push $IMAGE_URI

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3

      - name: Inicializar Terraform
        working-directory: terraform
        run: terraform init

      - name: Aplicar Terraform (Deploy com imagem versionada)
        working-directory: terraform
        run: terraform apply -auto-approve -var="image_uri=$IMAGE_URI"
