name: Build and Deploy API

on:
  repository_dispatch:
    types: [redeploy-api]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: quantum-api
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Gerar versão da imagem
        id: version
        run: |
          DATE=$(date +%Y%m%d)
          SHORT_SHA=${GITHUB_SHA::7}
          IMAGE_TAG="v${DATE}-${SHORT_SHA}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build, tag, and push Docker image
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy with Terraform
        working-directory: terraform/
        run: |
          terraform init
          terraform apply -auto-approve -var="image_uri=$IMAGE_URI"
